### ISSUE TITLE
문장에 '즤'라는 음절이 들어가면 NPE 발생

### ISSUE THREAD

**Issue by LeeTaeHyun94** [shineware/KOMORAN#148]
## 문제 설명
```
java.lang.NullPointerException: null
	at kr.co.shineware.nlp.komoran.core.model.Lattice.putIrregularExtendTokens(Lattice.java:160)
	at kr.co.shineware.nlp.komoran.core.model.Lattice.put(Lattice.java:144)
	at kr.co.shineware.nlp.komoran.core.Komoran.insertLattice(Komoran.java:563)
	at kr.co.shineware.nlp.komoran.core.Komoran.irregularParsing(Komoran.java:556)
	at kr.co.shineware.nlp.komoran.core.Komoran.analyze(Komoran.java:243)
	at kr.co.shineware.nlp.komoran.core.Komoran.analyze(Komoran.java:189)
```
문장에 ‘즤’라는 음절이 들어가면 위와 같이 NPE가 발생합니다

## 재현 경로
'즤' 음절을 포함한 문장을 검사 (예: 엘즤, 가즤)

## 기대 상황
형태소 분석 결과에는 에러가 없어야 할 것 같습니다.

## 환경 정보
_어떤 환경에서 이 문제가 발생하였나요?_
* OS 종류 / 버전:
* 브라우저 종류 및 버전:
* Komoran 버전: [3.3.9](https://github.com/shineware/KOMORAN/releases/tag/3.3.9)
* Java 버전: Java 11, Java 17

**Comment by gamamoe** [comment]
@LeeTaeHyun94 안녕하세요, 업데이트가 늦었습니다. 시간이 좀 지연되고 있어서 지금까지 확인한 내용에 대해서 우선 알려드리고 계속 이슈 확인하겠습니다. 아마 다른 방식으로 이미 진행하셨을 것 같은데, 혹시 여전히 문제 해결에 어려움이 있으시다면 임시적으로 `com.github.shin285:KOMORAN:3.4.0-beta` 버전을 사용하시면 이슈의 NPE는 발생하지 않을 것 같습니다

- 3.3.9 버전에서 이슈의 내용 재현이 확인됨
- 최신 master branch 코드 기준으로는 NPE 발생하지 않음
- (추가) 3.4.0-beta 버전에서 NPE 발생하지 않는 것 확인 (e.g., 엘즤 -> 엘/NNP 즤/NP)

@shin285 3.3.9 릴리즈와 현재 master 사이에 혹시 의심되는 code 부분이 있을까요? 만약 master 스냅샷에서 보고 된 이슈가 이미 해결된 것이 맞는다면 신규 버전 3.4.0 으로 아티팩트 배포를 통해서 이슈 해결이 가능할 것 같습니다. 어떻게 생각하세요?

**Comment by shin285** [comment]
@gamamoe 네 저도 같은 현상으로 재현이 되네요. 트레이닝 데이터에 따른 이슈인 것 같습니다. 말씀하신대로 신규 배포를 진행하는게 좋을 것 같습니다.

**Comment by LeeTaeHyun94** [comment]
넵 답변 감사합니다..! 다음버전에서 해결된 이슈라면 다행이네요
